AWSTemplateFormatVersion: 2010-09-09
Description:  cloudride home assignment - create vpc with 2 public subnets and 2 private subnets, connect IG and Nat Gateway
Parameters: {}
Resources:
# Create a VPC
  Task1VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Task 1 VPC

# Create 2 public subnets in 2 AZ
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref Task1VPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: Public Subnet 1 in AZ A

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref Task1VPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: Public Subnet 2 in AZ B

# Create 2 private subnets in 2 AZ
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref Task1VPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: Private Subnet 1 in AZ A

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref Task1VPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: Private Subnet 2 in AZ B

## Create IG and Attach to VPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: keyname
          Value: value

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Task1VPC
      InternetGatewayId: !Ref InternetGateway
